if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# zsh
setopt interactivecomments
autoload bashcompinit && bashcompinit
autoload -Uz compinit
compinit -iC
setopt transient_rprompt
setopt nonomatch

AWS_COMPLETER=$(which aws_completer)
complete -C "${AWS_COMPLETER}" aws

autoload -Uz add-zsh-hook
add-zsh-hook precmd _terminal-set-titles-hostname
export HISTORY_IGNORE="(cd|pwd|exit|l[sal]|ls -*)"

# PATH
export PATH=~/.local/bin:$PATH
export PATH=~/.docker/bin:$PATH
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"

# dircolors
eval `dircolors ~/.dircolors`

# git-flow-completion
if [ -d "$HOME/.dotfiles/git-flow-completion" ]; then
  source "$HOME/.dotfiles/git-flow-completion/git-flow-completion.zsh" 2>/dev/null
fi

# gcloud-sdk
if [ -d "/usr/share/google-cloud-sdk" ]; then
  source "/usr/share/google-cloud-sdk/completion.zsh.inc"
fi

# alias
alias sshp="ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no"
alias sshc='ssh -F ssh_config'
alias dc="docker-compose"
alias ls="ls --color=auto"

case "$(uname -r)" in
  *ARCH*)
    alias unzip="unzip -O CP933"
    alias open="xdg-open"
    alias pbcopy="xsel --clipboard --input"
    ;;
  *microsoft-standard*)
    alias pbcopy="clip"
    export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"
    export PATH="$PATH:/mnt/c/Program Files/Oracle/VirtualBox"
    ;;
esac

function _terminal-set-titles-hostname {
  mycmd=(${(s: :)${1}})
  echo -ne "\ek$(hostname|awk 'BEGIN{FS="."}{print $1}'):$mycmd[1]\e\\"
}

eval "$(~/.local/bin/mise activate zsh)"
eval "$(~/.local/bin/mise completion zsh)"

eval "$(fzf --zsh)"

# -- Use fd instead of fzf --
export FZF_DEFAULT_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd --type=d --hidden --strip-cwd-prefix --exclude .git"

# Use fd (https://github.com/sharkdp/fd) for listing path candidates.
# - The first argument to the function ($1) is the base path to start traversal
# - See the source code (completion.{bash,zsh}) for the details.
_fzf_compgen_path() {
  fd --hidden --exclude .git . "$1"
}

## Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  fd --type=d --hidden --exclude .git . "$1"
}

source ~/.dotfiles/fzf-git.sh/fzf-git.sh

if [ -f ~/.zshrc.local ]; then
  source ~/.zshrc.local
fi

