if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# zsh
setopt interactivecomments
autoload -Uz compinit
compinit -C
setopt transient_rprompt
setopt nonomatch

autoload -Uz add-zsh-hook
add-zsh-hook precmd _terminal-set-titles-hostname
export HISTORY_IGNORE="(cd|pwd|exit|l[sal]|ls -*)"

# dircolors
eval `dircolors ~/.dircolors`

# git-flow-completion
if [ -d "$HOME/.dotfiles/git-flow-completion" ]; then
  source "$HOME/.dotfiles/git-flow-completion/git-flow-completion.zsh" 2>/dev/null
fi

# gcloud-sdk
if [ -d "/usr/share/google-cloud-sdk" ]; then
  source "/usr/share/google-cloud-sdk/completion.zsh.inc"
fi

# anyenv
if [ -d "$HOME/.anyenv" ]; then
  export PATH=$HOME/.anyenv/bin:$PATH
  eval "$(anyenv init - --no-rehash zsh)"
  export PATH=~/.anyenv/envs/phpenv/versions/$(phpenv version|cut -d" " -f1)/composer/vendor/bin:$PATH
  #export PATH=~/.anyenv/envs/nodenv/versions/$(nodenv version|cut -d" " -f1)/bin:$PATH
  #export PATH=~/.anyenv/envs/rbenv/versions/$(rbenv version|cut -d" " -f1)/bin:$PATH
fi

# PATH
export PATH=~/.local/bin:$PATH

# alias
alias sshp="ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no"
alias sshc='ssh -F ssh_config'
alias dc="docker-compose"
alias dcd="docker-compose exec php drush"
alias dcdc="docker-compose exec php vendor/bin/drupal"
alias dp="docker ps"

case "$(uname -r)" in
  *ARCH*)
    alias unzip="unzip -O CP933"
    alias open="xdg-open"
    alias pbcopy="xsel --clipboard --input"
    ;;
  *microsoft-standard*)
    alias pbcopy="clip"
    export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"
    export PATH="$PATH:/mnt/c/Program Files/Oracle/VirtualBox"
    ;;
esac

if [ -f ~/.zshrc.local ]; then
  source ~/.zshrc.local
fi

function _terminal-set-titles-hostname {
  mycmd=(${(s: :)${1}})
  echo -ne "\ek$(hostname|awk 'BEGIN{FS="."}{print $1}'):$mycmd[1]\e\\"
}

